"""all except admin 

Revision ID: da49723b448c
Revises: 247c82a72ea2
Create Date: 2022-06-01 08:55:26.616031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da49723b448c'
down_revision = '247c82a72ea2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filiere',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.Column('nom', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('jour',
    sa.Column('nom', sa.String(length=10), nullable=False),
    sa.Column('num', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('nom')
    )
    op.create_table('niveau',
    sa.Column('code', sa.String(length=6), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('plage_horaire',
    sa.Column('id_plage', sa.Integer(), nullable=False),
    sa.Column('heure_debut', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.Column('heure_fin', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_plage')
    )
    op.create_table('salle',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('effectif', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('type_seance',
    sa.Column('nom', sa.String(length=10), nullable=False),
    sa.Column('duree', sa.Time(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('nom')
    )
    op.create_table('classe',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('effectif', sa.Integer(), nullable=False),
    sa.Column('niveau', sa.String(length=6), nullable=False),
    sa.Column('code_filiere', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['code_filiere'], ['filiere.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['niveau'], ['niveau.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('enseignant',
    sa.Column('matricule', sa.String(length=10), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('login', sa.String(length=50), nullable=False),
    sa.Column('code_filiere', sa.String(length=6), nullable=False),
    sa.ForeignKeyConstraint(['code_filiere'], ['filiere.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('matricule'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login')
    )
    op.create_table('activite',
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('date_act', sa.Date(), server_default=sa.text('now()'), nullable=False),
    sa.Column('matricule_enseignant', sa.String(length=10), nullable=False),
    sa.Column('id_plage', sa.Integer(), nullable=False),
    sa.Column('code_salle', sa.String(length=10), nullable=False),
    sa.Column('nom_jour', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['code_salle'], ['salle.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_plage'], ['plage_horaire.id_plage'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matricule_enseignant'], ['enseignant.matricule'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nom_jour'], ['jour.nom'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('nom')
    )
    op.create_table('specialite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('effectif', sa.Integer(), nullable=False),
    sa.Column('code_classe', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['code_classe'], ['classe.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cours',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('semestre', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=50), nullable=False),
    sa.Column('id_specialite', sa.Integer(), nullable=False),
    sa.Column('code_classe', sa.String(length=10), nullable=False),
    sa.Column('code_filiere', sa.String(length=6), nullable=False),
    sa.Column('nom_seance', sa.String(length=10), nullable=False),
    sa.Column('matricule_enseignant', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['code_classe'], ['classe.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_filiere'], ['filiere.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_specialite'], ['specialite.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matricule_enseignant'], ['enseignant.matricule'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nom_seance'], ['type_seance.nom'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('programmer',
    sa.Column('code_cours', sa.String(length=10), nullable=False),
    sa.Column('id_plage', sa.Integer(), nullable=False),
    sa.Column('code_salle', sa.String(length=50), nullable=False),
    sa.Column('nom_jour', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['code_cours'], ['cours.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['code_salle'], ['salle.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_plage'], ['plage_horaire.id_plage'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nom_jour'], ['jour.nom'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('code_cours', 'id_plage', 'code_salle', 'nom_jour')
    )
    op.create_unique_constraint("admin_login", 'admin', ['login'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("admin_login", 'admin', type_='unique')
    op.drop_table('programmer')
    op.drop_table('cours')
    op.drop_table('specialite')
    op.drop_table('activite')
    op.drop_table('enseignant')
    op.drop_table('classe')
    op.drop_table('type_seance')
    op.drop_table('salle')
    op.drop_table('plage_horaire')
    op.drop_table('niveau')
    op.drop_table('jour')
    op.drop_table('filiere')
    # ### end Alembic commands ###
